#!/usr/bin/env bash

set -e

while [[ $# -gt 0 ]]; do
    case "$1" in
        --profile-cpu)
            PROFILE_CPU=true
            CPU_PROFILE_OUTPUT_PATH="$2"

            CPU_PROFILE_ARG="--profile-cpu $CPU_PROFILE_OUTPUT_PATH"
            shift 2;;
        --drive-upload)
            DRIVE_SERVICE_ACCOUNT_CREDENTIALS_URL=$2
            DRIVE_UPLOAD_DIR=$3

            DRIVE_UPLOAD_ARG="--drive-upload $DRIVE_SERVICE_ACCOUNT_CREDENTIALS_URL $DRIVE_UPLOAD_DIR/test_pipeline_mes.csv $DRIVE_UPLOAD_DIR/test_pipeline_ind.csv $DRIVE_UPLOAD_DIR/test_pipeline_production.csv"
            shift 3;;
        --)
            shift
            break;;
        *)
            break;;
    esac
done

if [ $# -ne 2 ]; then
    echo "Usage: ./3_generate_outputs.sh [--drive-upload <drive-service-account-credentials-url> <drive-upload-dir>] <user> <data-root>"
    echo "Generates the outputs needed downstream from raw data files generated by step 2 and uploads to Google Drive"
    exit
fi

USER=$1
DATA_ROOT=$2

mkdir -p "$DATA_ROOT/Coded Coda Files"
mkdir -p "$DATA_ROOT/Pipeline Outputs"

./docker-run.sh ${CPU_PROFILE_ARG} ${DRIVE_UPLOAD_ARG} \
    "$USER" "$DATA_ROOT/UUIDs/phone_uuids.json" \
    "$DATA_ROOT/Raw Data/water_filter_poll.json" "$DATA_ROOT/Raw Data/internet_working_poll.json" \
    "$DATA_ROOT/Raw Data/waste_disposal_satisfaction.json" "$DATA_ROOT/Raw Data/demogs.json" \
    "$DATA_ROOT/Coded Coda Files" "$DATA_ROOT/Pipeline Outputs/traced_data.JSON" \
    "$DATA_ROOT/Pipeline Outputs/ICR" "$DATA_ROOT/Coda Files/" \
    "$DATA_ROOT/Pipeline Outputs/test_pipeline_mes.csv" "$DATA_ROOT/Pipeline Outputs/test_pipeline_ind.csv" \
    "$DATA_ROOT/Pipeline Outputs/test_pipeline_production.csv"
